version: "3.8"

services:
  mongodb-example:
    container_name: "mongodb-example"
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - "./binds-mongo:/data/db"
  mongoexpress-example:
    container_name: "mongoexpress-example"
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-example
    restart: always
