version: "3.8"
services:
  nginx-example:
    image: nginx:latest
    container_name: nginx-example
    ports:
      - "80:80"
    networks:
      - networks-example

networks:
  networks-example:
    driver: bridge
    name: networks-example
