version: "3.7"
services:
  example-laravel-app:
    build:
      args:
        user: andisugara
        uid: 503
      context: ./
      dockerfile: Dockerfile
    image: example-laravel
    container_name: example-laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - example-laravel-networks

  example-laravel-nginx:
    image: nginx:alpine
    container_name: example-laravel-nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - example-laravel-networks

  example-laravel-mysql:
    image: mysql:latest
    container_name: example-laravel-mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - example-laravel-networks
networks:
  example-laravel-networks:
    driver: bridge
