version: "3.8"

services:
  nginx-resourcelimit:
    container_name: nginx-resourcelimit
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50M
        limits:
          cpus: "0.50"
          memory: 100M
