version: "3.8"

services:
  mongo-data:
    image: mongo:latest
    container_name: mongo-data
    volumes:
      - mongo-data1:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017

volumes:
  mongo-data1:
    name: mongo-data1
